URL_SERVICE = "https://d75fb003-9547-4bb1-a35f-d416bc93d4f6.serverhub.praktikum-services.ru"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
DOC_PATH = "/docs/"
CREATE_USER_PATH = "/api/v1/users/"
CREATE_KITS_PATH = "/api/v1/kits/"
